branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: myhiddenplace-sever
  branch: master
  default_platform: Node.js
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
